### ISSUE TITLE
No longer require workarounds for targeting values in async.

### ISSUE THREAD

**Issue by ghost** [AmazingMech2418/ScratchCloud#4]
In async, you are able to wait until a value in a cloud variable is equal to another value. However, you are not able to wait until a value is not equal to another value. This is the same case with greater and less than. This would make it much easier to target values in async.

**Comment by AmazingMech2418** [comment]
The ideal way to go about this would probably be to enable using functions for checking values. This is a pretty large feature request though, and the only issue is backwards compatibility with the old system.

**Comment by ghost** [comment]
In that case, the targeting might need to be refactored a little bit.

**Comment by AmazingMech2418** [comment]
I could possibly add some pseudo-overloading, but I'm not sure if that would work to preserve the backwards compatibility.

**Comment by ghost** [comment]
> I could possibly add some pseudo-overloading, but I'm not sure if that would work to preserve the backwards compatibility.

That would work!
