### ISSUE TITLE
Only allow cloud.get to be used when all cloud variables are loaded.

### ISSUE THREAD

**Issue by ghost** [AmazingMech2418/ScratchCloud#6]
When using cloud.on('set') it waits until all the cloud variables have been loaded to run the command. The same with cloud.get would allow you to use the function cloud.get before the cloud variables have loaded. However, it has to wait until every cloud variable has been loaded.

**Comment by AmazingMech2418** [comment]
I'm not sure how this would work... 

Also, `cloud.on('set')` just handles variable change events. It doesn't wait until all variables are loaded.

Also, I'm not sure if it is possible to tell what all of the cloud variables are in the first place.

**Comment by ghost** [comment]
> I'm not sure how this would work...
> 
> Also, `cloud.on('set')` just handles variable change events. It doesn't wait until all variables are loaded.
> 
> Also, I'm not sure if it is possible to tell what all of the cloud variables are in the first place.

By doing that (on the client), it automatically has to wait until they're loaded.

**Comment by AmazingMech2418** [comment]
An onload function might be good. Like this:
```js
cloud.onload("variable", () => {/* your code */});
```

Of course an async version too though! XD

**Comment by ghost** [comment]
> An onload function might be good. Like this:
> 
> ```js
> cloud.onload("variable", () => {/* your code */});
> ```
> 
> Of course an async version too though! XD

That would work!

**Comment by ghost** [comment]
For async:
 ```js
await new Promise((resolve, reject) => {
        cloud.on("set", (name, value) => {
            if(name == varname) resolve(); // The cloud variable name should be replaced where it says varname
        });
    });
```
